// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StadiumAPI.Data;

#nullable disable

namespace StadiumAPI.Migrations
{
    [DbContext(typeof(StadiumDbContext))]
    [Migration("20250811113506_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StadiumAPI.Models.Courts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Số 1",
                            PricePerHour = 300000m,
                            SportType = "Bóng đá",
                            StadiumId = 1,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Số 2",
                            PricePerHour = 350000m,
                            SportType = "Bóng đá",
                            StadiumId = 1,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân A",
                            PricePerHour = 80000m,
                            SportType = "Cầu lông",
                            StadiumId = 2,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            Name = "Sân B",
                            PricePerHour = 90000m,
                            SportType = "Cầu lông",
                            StadiumId = 2,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Rổ 1",
                            PricePerHour = 120000m,
                            SportType = "Bóng rổ",
                            StadiumId = 3,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Tennis 1",
                            PricePerHour = 200000m,
                            SportType = "Tennis",
                            StadiumId = 4,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Tennis 2",
                            PricePerHour = 220000m,
                            SportType = "Tennis",
                            StadiumId = 4,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Chuyền 1",
                            PricePerHour = 100000m,
                            SportType = "Bóng chuyền",
                            StadiumId = 5,
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StadiumAPI.Models.StadiumImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StadiumImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/sanbong-cantho-1.jpg",
                            StadiumId = 1,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/sanbong-cantho-2.jpg",
                            StadiumId = 1,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/sancaulong-cantho-1.jpg",
                            StadiumId = 2,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://example.com/sancaulong-cantho-2.jpg",
                            StadiumId = 2,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://example.com/sanro-cantho-1.jpg",
                            StadiumId = 3,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://example.com/santennis-cantho-1.jpg",
                            StadiumId = 4,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://example.com/sanchuyen-cantho-1.jpg",
                            StadiumId = 5,
                            UploadedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StadiumAPI.Models.Stadiums", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUser")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stadiums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nguyễn Văn Cừ, Quận Ninh Kiều, Cần Thơ",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng đá cỏ nhân tạo chất lượng cao, phù hợp thi đấu và tập luyện.",
                            IsApproved = true,
                            Latitude = 10.045162m,
                            Longitude = 105.746857m,
                            Name = "Sân Bóng Cỏ Nhân Tạo Nguyễn Văn Cừ",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Số 1 Lê Lợi, Quận Ninh Kiều, Cần Thơ",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân cầu lông tiêu chuẩn, phù hợp thi đấu chuyên nghiệp.",
                            IsApproved = true,
                            Latitude = 10.03711m,
                            Longitude = 105.78829m,
                            Name = "Trung Tâm Cầu Lông Lê Lợi",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Phường Hưng Lợi, Quận Ninh Kiều, Cần Thơ",
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng rổ ngoài trời, rộng rãi, thoáng mát.",
                            IsApproved = true,
                            Latitude = 10.0298m,
                            Longitude = 105.7621m,
                            Name = "Sân Bóng Rổ Hưng Lợi",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Phường An Bình, Quận Ninh Kiều, Cần Thơ",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân tennis tiêu chuẩn với hệ thống đèn ban đêm.",
                            IsApproved = true,
                            Latitude = 10.0515m,
                            Longitude = 105.7723m,
                            Name = "Sân Tennis An Bình",
                            OpenTime = new TimeSpan(0, 5, 30, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Trường Đại học Cần Thơ, Quận Ninh Kiều, Cần Thơ",
                            CloseTime = new TimeSpan(0, 18, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng chuyền ngoài trời cho sinh viên và cộng đồng.",
                            IsApproved = true,
                            Latitude = 10.0299m,
                            Longitude = 105.7702m,
                            Name = "Sân Bóng Chuyền Cần Thơ University",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
