// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StadiumAPI.Data;

#nullable disable

namespace StadiumAPI.Migrations
{
    [DbContext(typeof(StadiumDbContext))]
    [Migration("20250911044928_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StadiumAPI.Models.CourtRelations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildCourtId")
                        .HasColumnType("int");

                    b.Property<int>("ParentCourtId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildCourtId");

                    b.HasIndex("ParentCourtId");

                    b.ToTable("CourtRelations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildCourtId = 2,
                            ParentCourtId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChildCourtId = 3,
                            ParentCourtId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChildCourtId = 20,
                            ParentCourtId = 19
                        },
                        new
                        {
                            Id = 4,
                            ChildCourtId = 21,
                            ParentCourtId = 19
                        },
                        new
                        {
                            Id = 5,
                            ChildCourtId = 35,
                            ParentCourtId = 34
                        },
                        new
                        {
                            Id = 6,
                            ChildCourtId = 36,
                            ParentCourtId = 34
                        });
                });

            modelBuilder.Entity("StadiumAPI.Models.Courts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("Courts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 7 người",
                            PricePerHour = 300000m,
                            SportType = "Bóng đá sân 7",
                            StadiumId = 1,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 5 người A",
                            PricePerHour = 200000m,
                            SportType = "Bóng đá sân 5",
                            StadiumId = 1,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 5 người B",
                            PricePerHour = 200000m,
                            SportType = "Bóng đá sân 5",
                            StadiumId = 1,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân A",
                            PricePerHour = 50000m,
                            SportType = "Cầu lông",
                            StadiumId = 2,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            Name = "Sân B",
                            PricePerHour = 50000m,
                            SportType = "Cầu lông",
                            StadiumId = 2,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Số 1",
                            PricePerHour = 100000m,
                            SportType = "Tennis",
                            StadiumId = 3,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Số 2",
                            PricePerHour = 100000m,
                            SportType = "Tennis",
                            StadiumId = 3,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân chính",
                            PricePerHour = 150000m,
                            SportType = "Bóng rổ",
                            StadiumId = 4,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 1",
                            PricePerHour = 70000m,
                            SportType = "Cầu lông",
                            StadiumId = 5,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            Name = "Sân 2",
                            PricePerHour = 70000m,
                            SportType = "Cầu lông",
                            StadiumId = 5,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Chính",
                            PricePerHour = 500000m,
                            SportType = "Bóng đá sân 11",
                            StadiumId = 6,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 1",
                            PricePerHour = 120000m,
                            SportType = "Tennis",
                            StadiumId = 8,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 2",
                            PricePerHour = 120000m,
                            SportType = "Tennis",
                            StadiumId = 8,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Số 1",
                            PricePerHour = 60000m,
                            SportType = "Cầu lông",
                            StadiumId = 9,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Số 2",
                            PricePerHour = 60000m,
                            SportType = "Cầu lông",
                            StadiumId = 9,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Đơn",
                            PricePerHour = 150000m,
                            SportType = "Tennis",
                            StadiumId = 10,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Chính",
                            PricePerHour = 80000m,
                            SportType = "Bóng chuyền",
                            StadiumId = 11,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            Name = "Sân Số 3",
                            PricePerHour = 75000m,
                            SportType = "Cầu lông",
                            StadiumId = 13,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 7 người 1",
                            PricePerHour = 280000m,
                            SportType = "Bóng đá sân 7",
                            StadiumId = 14,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 5 người A",
                            PricePerHour = 180000m,
                            SportType = "Bóng đá sân 5",
                            StadiumId = 14,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 5 người B",
                            PricePerHour = 180000m,
                            SportType = "Bóng đá sân 5",
                            StadiumId = 14,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Công an 1",
                            PricePerHour = 110000m,
                            SportType = "Tennis",
                            StadiumId = 15,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân chính",
                            PricePerHour = 100000m,
                            SportType = "Bóng rổ",
                            StadiumId = 16,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân A",
                            PricePerHour = 50000m,
                            SportType = "Cầu lông",
                            StadiumId = 17,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Bóng Chuyền",
                            PricePerHour = 70000m,
                            SportType = "Bóng chuyền",
                            StadiumId = 17,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 7 người 1",
                            PricePerHour = 250000m,
                            SportType = "Bóng đá sân 7",
                            StadiumId = 18,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 5 người",
                            PricePerHour = 150000m,
                            SportType = "Bóng đá sân 5",
                            StadiumId = 18,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 1",
                            PricePerHour = 90000m,
                            SportType = "Tennis",
                            StadiumId = 19,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân bóng chuyền",
                            PricePerHour = 80000m,
                            SportType = "Bóng chuyền",
                            StadiumId = 20,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân Pickleball 1",
                            PricePerHour = 100000m,
                            SportType = "Pickleball",
                            StadiumId = 22,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 1",
                            PricePerHour = 70000m,
                            SportType = "Cầu lông",
                            StadiumId = 23,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 2",
                            PricePerHour = 70000m,
                            SportType = "Cầu lông",
                            StadiumId = 23,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân chính",
                            PricePerHour = 150000m,
                            SportType = "Bóng chuyền",
                            StadiumId = 24,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 11 người",
                            PricePerHour = 450000m,
                            SportType = "Bóng đá sân 11",
                            StadiumId = 25,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 7 người A",
                            PricePerHour = 300000m,
                            SportType = "Bóng đá sân 7",
                            StadiumId = 25,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Sân 7 người B",
                            PricePerHour = 300000m,
                            SportType = "Bóng đá sân 7",
                            StadiumId = 25,
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StadiumAPI.Models.StadiumImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("StadiumImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "img/b1a94c40-8a6e-4686-a56e-edde8ce9a985.jpg",
                            StadiumId = 1,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "img/b1a94c40-8a6e-4686-a56e-edde8ce9a985.jpg",
                            StadiumId = 1,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "img/bb61649d-80de-4dda-bda0-2e5de31b77a6.jpg",
                            StadiumId = 2,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "img/b5768826-c8f4-4af1-9e1f-1dcee9d6ec56.jpg",
                            StadiumId = 3,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "img/ab4060d7-7676-4728-b6bd-c54de7031f16.jpg",
                            StadiumId = 2,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "img/57cd9906-494d-48b9-9448-c446191b295d.jpg",
                            StadiumId = 2,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "img/2647a365-74eb-4c0e-8fc3-2c5c4fd3cda1.jpg",
                            StadiumId = 3,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "img/2a4f38ac-e941-45cc-ad2b-c76d9d37d392.jpg",
                            StadiumId = 3,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "img/874f1c5a-e37a-4f1e-a002-5fcf803e6a03.jpg",
                            StadiumId = 4,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "img/bb5b3b93-05ba-4701-9a56-52a300fe1504.jpeg",
                            StadiumId = 5,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "img/0ebe27dc-12ab-44cd-8ea7-95e234a94e6a.jpg",
                            StadiumId = 5,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "img/e36d13a7-23b3-4bfd-a421-0d370a2313ad.jpg",
                            StadiumId = 5,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "img/12bad99d-2b1b-48bc-a3a2-5b91cf0a9cff.jpg",
                            StadiumId = 6,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "img/adc0fc5e-6260-4a29-9e18-ac508157db11.jpg",
                            StadiumId = 6,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "img/9fc70741-ab78-4396-8165-067736a70416.jpg",
                            StadiumId = 6,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "img/b2f0a4aa-c4e1-45c6-90f2-e14faa85c406.png",
                            StadiumId = 8,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "img/37d7b03f-34cd-441d-ba51-2ae85c88188a.jpg",
                            StadiumId = 9,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "img/52e1d9bf-2f4f-48fc-a543-7f23e61e1395.jpg",
                            StadiumId = 9,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "img/9f0dc411-87a2-4a2d-b028-69dcf82fae39.jpg",
                            StadiumId = 10,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "img/e1b8daf3-81eb-4bf7-b9c0-522dd9f80838.jpg",
                            StadiumId = 11,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "img/b2c0e10d-5585-46cf-a576-cb24732e1538.jpg",
                            StadiumId = 11,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "img/ba1b77bf-0ae7-4a44-bf2a-e6d9c31fe6e0.jpg",
                            StadiumId = 13,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "img/2ec2068b-e1d7-48eb-abb6-fd5a1612ec29.jpg",
                            StadiumId = 13,
                            UploadedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "img/1c002bd0-f1ab-47c9-8871-87aa55f99d15.jpg",
                            StadiumId = 14,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "img/7c2f592e-9db8-4ad7-b378-ceb4ee75b3db.jpg",
                            StadiumId = 14,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "img/8da36e7f-6699-4da4-9622-da8310ba734b.jpg",
                            StadiumId = 16,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "img/a4b0822d-b2cc-4102-9192-056740ea1e11.jpg",
                            StadiumId = 17,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "img/21a9b32a-bede-4c9b-984f-db32070b4a22.jpg",
                            StadiumId = 18,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "img/364ddf95-6df0-426f-86a1-7923eedc03de.jpg",
                            StadiumId = 19,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "img/93d0cd83-6917-4d56-870c-871c4d63e036.jpg",
                            StadiumId = 20,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "img/41b18406-815d-4f10-9140-5e3a3c9e6d08.jpg",
                            StadiumId = 22,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "img/25e1be93-6df3-4507-a7f7-201e602afa7f.jpg",
                            StadiumId = 23,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "img/25e1be93-6df3-4507-a7f7-201e602afa7f.jpg",
                            StadiumId = 24,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "img/25e1be93-6df3-4507-a7f7-201e602afa7f.jpg",
                            StadiumId = 25,
                            UploadedAt = new DateTime(2025, 8, 17, 13, 38, 21, 454, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StadiumAPI.Models.StadiumVideos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("StadiumVideos", (string)null);
                });

            modelBuilder.Entity("StadiumAPI.Models.Stadiums", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressUnsigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUser")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameUnsigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stadiums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Đường Cách Mạng Tháng Tám, Bình Thủy, Cần Thơ",
                            AddressUnsigned = "duong cach mang thang tam, binh thuy, can tho",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng đá cỏ nhân tạo chất lượng cao với hệ thống đèn LED hiện đại.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0528m,
                            Longitude = 105.7725m,
                            Name = "Sân Bóng Phi Long",
                            NameUnsigned = "san bong phi long",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Số 45 Cách Mạng Tháng Tám, Cái Khế, Bình Thủy, Cần Thơ",
                            AddressUnsigned = "so 45 cach mang thang tam, cai khe, binh thuy, can tho",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Cụm sân cầu lông rộng rãi, có hệ thống ánh sáng tốt và dịch vụ chuyên nghiệp.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0401m,
                            Longitude = 105.7684m,
                            Name = "Sân Cầu Lông Quang Sport",
                            NameUnsigned = "san cau long quang sport",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Đường Nguyễn Đệ, An Hòa, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "duong nguyen de, an hoa, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân tennis tiêu chuẩn, phù hợp cho người mới bắt đầu và cả vận động viên chuyên nghiệp.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0381m,
                            Longitude = 105.7788m,
                            Name = "Sân Tennis 6 Đời 6",
                            NameUnsigned = "san tennis 6 doi 6",
                            OpenTime = new TimeSpan(0, 5, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "168 Nguyễn Văn Cừ Nối Dài, An Bình, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "168 nguyen van cu noi dai, an binh, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng rổ rộng rãi với mặt sân và vành rổ đạt chuẩn, thích hợp cho việc tập luyện và thi đấu.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0163m,
                            Longitude = 105.7539m,
                            Name = "Sân bóng rổ DNC",
                            NameUnsigned = "san bong ro dnc",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Số 15A/1 Hẻm 51, Đường 3-2, An Khánh, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "so 15a/1 hem 51, duong 3-2, an khanh, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 21, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân cầu lông trong nhà với hệ thống chiếu sáng và không gian sạch sẽ.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0249m,
                            Longitude = 105.7687m,
                            Name = "Sân Cầu Lông Tambo",
                            NameUnsigned = "san cau long tambo",
                            OpenTime = new TimeSpan(0, 5, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Đường Lê Lợi, Cái Khế, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "duong le loi, cai khe, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân vận động đa năng lớn nhất khu vực, phù hợp cho nhiều sự kiện thể thao lớn.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0396m,
                            Longitude = 105.7725m,
                            Name = "Sân Vận Động Cần Thơ",
                            NameUnsigned = "san van dong can tho",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Phú Thứ, Cái Răng, Cần Thơ",
                            AddressUnsigned = "phu thu, cai rang, can tho",
                            CloseTime = new TimeSpan(0, 21, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Cụm sân tennis với mặt sân chất lượng cao, phục vụ luyện tập và thi đấu.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0094m,
                            Longitude = 105.7877m,
                            Name = "Sân Tennis 586",
                            NameUnsigned = "san tennis 586",
                            OpenTime = new TimeSpan(0, 5, 30, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "79 Trần Phú, Cái Khế, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "79 tran phu, cai khe, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            CreatedByUser = 2,
                            Description = "Sân cầu lông trong nhà với không gian rộng rãi, thoáng mát, thích hợp cho việc tập luyện và thi đấu.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0331m,
                            Longitude = 105.7770m,
                            Name = "Sân Cầu Lông Bưu Điện Cần Thơ",
                            NameUnsigned = "san cau long buu dien can tho",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Cái Khế, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "cai khe, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 23, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            CreatedByUser = 3,
                            Description = "Sân tennis thuộc khuôn viên khách sạn Mường Thanh, đạt tiêu chuẩn quốc tế, có đèn chiếu sáng ban đêm.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0347m,
                            Longitude = 105.7761m,
                            Name = "Sân Tennis Mường Thanh",
                            NameUnsigned = "san tennis muong thanh",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Address = "96 Chu Văn An, An Khánh, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "96 chu van an, an khanh, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng chuyền ngoài trời, là nơi giao lưu của các đội bóng mạnh trong khu vực.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0240m,
                            Longitude = 105.7725m,
                            Name = "Sân bóng chuyền 586",
                            NameUnsigned = "san bong chuyen 586",
                            OpenTime = new TimeSpan(0, 5, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Hẻm liên tổ 4-5, Hưng Lợi, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "hem lien to 4-5, hung loi, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân cầu lông tư nhân, có nhiều sân con, không gian thoáng đãng.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0152m,
                            Longitude = 105.7629m,
                            Name = "Sân Cầu Lông Hoàng Long",
                            NameUnsigned = "san cau long hoang long",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Address = "37 Đường B3, Hưng Lợi, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "37 duong b3, hung loi, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 22, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            CreatedByUser = 2,
                            Description = "Sân bóng đá cỏ nhân tạo 7 người, là địa điểm quen thuộc của các đội bóng phong trào.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0195m,
                            Longitude = 105.7620m,
                            Name = "Sân bóng đá Anh Tuấn",
                            NameUnsigned = "san bong da anh tuan",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Đường Trần Phú, Cái Khế, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "duong tran phu, cai khe, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            CreatedByUser = 3,
                            Description = "Sân tennis thuộc khu vực Công an thành phố, chất lượng tốt, có hệ thống đèn.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0315m,
                            Longitude = 105.7765m,
                            Name = "Sân Tennis Công An Cần Thơ",
                            NameUnsigned = "san tennis cong an can tho",
                            OpenTime = new TimeSpan(0, 5, 30, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Address = "Khu dân cư Hậu Thạnh Mỹ, Lê Bình, Cái Răng, Cần Thơ",
                            AddressUnsigned = "khu dan cu hau thanh my, le binh, cai rang, can tho",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 4,
                            CreatedByUser = 4,
                            Description = "Sân bóng rổ ngoài trời, rộng rãi, thường xuyên tổ chức các giải đấu phong trào.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0035m,
                            Longitude = 105.7876m,
                            Name = "Sân bóng rổ WestSide Tây Đô",
                            NameUnsigned = "san bong ro westside tay do",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Address = "Quốc lộ 61, Vị Tân, Vị Thanh, Hậu Giang",
                            AddressUnsigned = "quoc lo 61, vi tan, vi thanh, hau giang",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Nhà thi đấu đa năng, tổ chức các môn thể thao trong nhà như bóng chuyền, cầu lông, bóng rổ.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 9.7761m,
                            Longitude = 105.4746m,
                            Name = "Nhà Thi Đấu Vị Thanh",
                            NameUnsigned = "nha thi dau vi thanh",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Address = "Đường 19/8, Vị Tân, Vị Thanh, Hậu Giang",
                            AddressUnsigned = "duong 19/8, vi tan, vi thanh, hau giang",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            CreatedByUser = 2,
                            Description = "Sân bóng đá cỏ nhân tạo chất lượng cao, thường xuyên tổ chức các giải đấu phong trào tại Hậu Giang.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 9.7825m,
                            Longitude = 105.4851m,
                            Name = "Sân bóng đá Vị Thanh",
                            NameUnsigned = "san bong da vi thanh",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Address = "Phường 7, Vị Thanh, Hậu Giang",
                            AddressUnsigned = "phuong 7, vi thanh, hau giang",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 3,
                            CreatedByUser = 3,
                            Description = "Cụm sân tennis tiêu chuẩn, có đèn chiếu sáng ban đêm.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 9.7912m,
                            Longitude = 105.4820m,
                            Name = "Sân Tennis Phú Hưng",
                            NameUnsigned = "san tennis phu hung",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Address = "Đường 1/5, Phường 1, Vĩnh Long",
                            AddressUnsigned = "duong 1/5, phuong 1, vinh long",
                            CloseTime = new TimeSpan(0, 21, 30, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Nhà thi đấu trung tâm tỉnh Vĩnh Long, thường tổ chức các sự kiện thể thao lớn.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.2458m,
                            Longitude = 105.9723m,
                            Name = "Nhà Thi Đấu Vĩnh Long",
                            NameUnsigned = "nha thi dau vinh long",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Address = "Đường 3 Tháng 2, Hưng Lợi, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "duong 3 thang 2, hung loi, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 21, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 4,
                            CreatedByUser = 4,
                            Description = "Sân Pickleball mới mở, phù hợp cho mọi lứa tuổi.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0240m,
                            Longitude = 105.7725m,
                            Name = "Sân Pickleball Cần Thơ",
                            NameUnsigned = "san pickleball can tho",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Address = "21 Phạm Hùng, Ba Láng, Cái Răng, Cần Thơ",
                            AddressUnsigned = "21 pham hung, ba lang, cai rang, can tho",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 4,
                            CreatedByUser = 4,
                            Description = "Cụm sân cầu lông hiện đại, hệ thống ánh sáng tốt, có ghế chờ cho người chơi.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0121m,
                            Longitude = 105.7954m,
                            Name = "Sân Cầu Lông Win Sport",
                            NameUnsigned = "san cau long win sport",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Address = "Khu du lịch sinh thái Cồn Ấu, Hưng Phú, Cái Răng, Cần Thơ",
                            AddressUnsigned = "khu du lich sinh thai con au, hung phu, cai rang, can tho",
                            CloseTime = new TimeSpan(0, 18, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            CreatedByUser = 1,
                            Description = "Sân bóng chuyền bãi biển tiêu chuẩn, không gian thoáng đãng.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0289m,
                            Longitude = 105.7997m,
                            Name = "Sân bóng chuyền bãi biển Cần Thơ",
                            NameUnsigned = "san bong chuyen bai bien can tho",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Address = "Đường 3 Tháng 2, Xuân Khánh, Ninh Kiều, Cần Thơ",
                            AddressUnsigned = "duong 3 thang 2, xuan khanh, ninh kieu, can tho",
                            CloseTime = new TimeSpan(0, 20, 0, 0, 0),
                            CreatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 2,
                            CreatedByUser = 2,
                            Description = "Sân bóng đá 11 người của Trường Đại học Cần Thơ, phục vụ sinh viên và cộng đồng.",
                            IsApproved = true,
                            IsLocked = false,
                            Latitude = 10.0299m,
                            Longitude = 105.7702m,
                            Name = "Sân bóng đá Đại học Cần Thơ",
                            NameUnsigned = "san bong da dai hoc can tho",
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            UpdatedAt = new DateTime(2025, 8, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StadiumAPI.Models.CourtRelations", b =>
                {
                    b.HasOne("StadiumAPI.Models.Courts", "ChildCourt")
                        .WithMany("ParentRelations")
                        .HasForeignKey("ChildCourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StadiumAPI.Models.Courts", "ParentCourt")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ParentCourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildCourt");

                    b.Navigation("ParentCourt");
                });

            modelBuilder.Entity("StadiumAPI.Models.Courts", b =>
                {
                    b.HasOne("StadiumAPI.Models.Stadiums", "Stadium")
                        .WithMany("Courts")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("StadiumAPI.Models.StadiumImages", b =>
                {
                    b.HasOne("StadiumAPI.Models.Stadiums", "Stadium")
                        .WithMany("StadiumImages")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("StadiumAPI.Models.StadiumVideos", b =>
                {
                    b.HasOne("StadiumAPI.Models.Stadiums", "Stadium")
                        .WithMany("StadiumVideos")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("StadiumAPI.Models.Courts", b =>
                {
                    b.Navigation("ChildRelations");

                    b.Navigation("ParentRelations");
                });

            modelBuilder.Entity("StadiumAPI.Models.Stadiums", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("StadiumImages");

                    b.Navigation("StadiumVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
